#!/bin/bash
echo "🔍 Verificando configuración..."
echo ""
echo "1️⃣  ¿Qué URL configuraste en Twilio Console?"
echo "   A) https://df4a6fec2ac0.ngrok-free.app (ngrok local)"
echo "   B) https://twilio-server-813030270163.us-central1.run.app (Cloud Run GCP)"
echo ""
echo "2️⃣  Verificando servicios activos:"
echo ""
echo "   Docker local (puerto 5000):"
curl -s http://localhost:5000/ 2>&1 | head -2 || echo "   ❌ No responde"
echo ""
echo "   Cloud Run GCP:"
curl -s https://twilio-server-813030270163.us-central1.run.app/ 2>&1 | head -2 || echo "   ❌ No responde"
echo ""
echo "3️⃣  Si usas Cloud Run, verifica que la BD esté en Cloud SQL"
echo "   Si usas Docker local, verifica que ngrok esté corriendo"
